### ISSUE TITLE
thanks a lot

### ISSUE THREAD

**Issue by cwr31** [xmark1/fanless-mini#1]
Thanks a lot. Could you update your efi here since you got a 2048M igpu memory？

**Comment by kratoskang** [comment]
one of the ethernet port can not work.

**Comment by xmark1** [comment]
> one of the ethernet port can not work.

For the right ethernet port you need SmallTree-Intel-211-AT-PCIe-GBE.kext (not included here).
The left one is supported by IntelMausiEthernet.kext, which is in this build.
